### PR TITLE
Local moveset data support (+Jigglypuff), few misc things

### PR DESCRIPTION
**Pull request by drakeirving**
Hey, so I'm bringing back the option for local move data files??

I basically started this because I use the calc pretty often and it's annoying that I have to fill in correct values every time I want to check something. I went to both KH and KH-API about contributing and didn't have much luck.

I did create the whole Jigglypuff moveset data file below. I modeled it off of the files taken from existing API queries, but I trimmed the stuff that the calc doesn't parse or has defaults for. The actual data was filled in through a process of scraping the *script viewer* and generating a data file (which I use for my own project https://github.com/drakeirving/ult-hitbox-viewer), then I wrote a kludgy converter to go from that moveset data to this API-like one... which then gets read by the calc. Honestly it would have been faster to just manually fill it in, but basically my point is all the data should be accurate.

I got the moveset loader to check for local files before calling the API; I think this makes the most sense. I just piggybacked off of the existing ajax loading but if you want to suggest a better method that would be fine.

I added handling for AdditionalHitstun and Effect parameters since Puff moves use these but they weren't fully implemented, as they aren't included in the API responses. I plopped these into the HitboxActive group because it seemed like the least amount of effort to get them to work. Effects are only validated by the calc if they're contained in the global effect list, and SetWeight is applied for the relevant ones.

I also fixed a bug where SetWeight would never be applied because a spot was missed where it still said shieldDamage from copying.

Sorry if the diffs have some messy bits, I think my editor automatically removed a bunch of random whitespace.

### CODE REVIEW

**Comment by rubendal** [comment]
This might be unfortunate but I have been working for some months on some changes to the calculator to use local data but I will be replacing the KH API support and data structure with one that is more focused on hitbox data by getting it from scripts similar to your own project by scraping them directly on script parser and param spreadsheet and some data added manually

Collaboration was one of the most important things I considered for this format as well as storing previous patch versions, the data is generated by a script reading a spreadsheet on Google Sheets, allowing multiple people to collaborate as well as duplicating the spreadsheet to save previous versions data
Example
Dark Pit: https://docs.google.com/spreadsheets/d/1TQ6MWP4zYXw_00fn7YVzzw4ul4W9Cthtd9gGzHi-1io/edit?usp=sharing

Note: Still working on it, I might add more stuff. Suggestions are also appreciated

This new format brings new changes to the calculator as well as having more data available instead of using KH API and adding more stuff to the parser which might not work if it's not added correctly

**Comment by drakeirving** [comment]
No, this is perfectly fine. Like yeah I did the work, but it isn't even really wasted since I've already been using my copy of the calc and can continue doing so until this is completed. Having an overhaul to make things easier to contribute and push to the calc in general is definitely preferred and directly solves the problem I had in the first place of it being too tightly dependent on KH.

**Comment by normandy447** [comment]
> Example
> Dark Pit: https://docs.google.com/spreadsheets/d/1TQ6MWP4zYXw_00fn7YVzzw4ul4W9Cthtd9gGzHi-1io/edit?usp=sharing
> 
> Note: Still working on it, I might add more stuff. Suggestions are also appreciated
> 
> This new format brings new changes to the calculator as well as having more data available instead of using KH API and adding more stuff to the parser which might not work if it's not added correctly

this is awesome! i know this is offtopic but could i ask for the ken google sheet? im working on my own "[calculator](https://docs.google.com/spreadsheets/d/1ft-9CtLFCE8AMq4RF8UMcKFKUw4tas4yC4_OjZt_usA/edit#gid=190291201)" but also had some trouble replicating your results, but at least KB works out

**Comment by rubendal** [comment]
@normandy447 Ken google sheet https://docs.google.com/spreadsheets/d/1a3GjjlIcVGILkr7ZWMZhlzxeUDzmIAMEkIExhvSoIRo/edit?usp=sharing

**Comment by drakeirving** [comment]
@rubendal As per your tweet, how would I go about contributing to get Puff up there? I can probably just like, do all of it if I know how.

**Comment by rubendal** [comment]
@drakeirving I will share the folder with all characters sheets so people can request edit access when I finish loading hitbox, grab and throw data on them and make a guide on how to fill it.

Puff sheet has the data loaded so you can request it and use Dark Pit and Ken sheets as a reference in the meantime https://docs.google.com/document/d/1OVTvJzsHqkvOPM4cH87sYKYhwOqZDNfCRdNHHohVpKs/edit?usp=sharing

**Comment by rubendal** [comment]
@drakeirving I will share the folder with all characters sheets so people can request edit access when I finish loading hitbox, grab and throw data on them and make a guide on how to fill it.

Puff sheet has the data loaded so you can request it and use Dark Pit and Ken sheets as a reference in the meantime https://docs.google.com/spreadsheets/d/1cjJRw4Uu8PE6oVvoOaS8CEl3x8hLIIK5Wy07Zkysji8/edit?usp=sharing

**Comment by rubendal** [comment]
Made a page on the wiki with the details regarding characters sheets structure, this should help to understand what it's needed to fill it and has the link to the folder with all character files + all scraped data for hitboxes, grabs and throws from scripts https://github.com/rubendal/SSBU-Calculator/wiki/How-to-contribute-on-calculator's-new-character-data-format

If anyone has any additional doubts, please let me know. I will also adjust the wiki page in case I missed something or additional details are needed

**Comment by normandy447** [comment]
> Made a page on the wiki with the details regarding characters sheets structure, this should help to understand what it's needed to fill it and has the link to the folder with all character files + all scraped data for hitboxes, grabs and throws from scripts https://github.com/rubendal/SSBU-Calculator/wiki/How-to-contribute-on-calculator's-new-character-data-format
> 
> If anyone has any additional doubts, please let me know. I will also adjust the wiki page in case I missed something or additional details are needed

Hello Ruben, hope youre doing good! if you would give me the link to kazuyas excel sheet (wasnt in the folder) i would love to contribute to him!

**Comment by rubendal** [comment]
> > Made a page on the wiki with the details regarding characters sheets structure, this should help to understand what it's needed to fill it and has the link to the folder with all character files + all scraped data for hitboxes, grabs and throws from scripts https://github.com/rubendal/SSBU-Calculator/wiki/How-to-contribute-on-calculator's-new-character-data-format
> > If anyone has any additional doubts, please let me know. I will also adjust the wiki page in case I missed something or additional details are needed
> 
> Hello Ruben, hope youre doing good! if you would give me the link to kazuyas excel sheet (wasnt in the folder) i would love to contribute to him!

Sorry for the delay, added Kazuya's sheet to the folder

https://docs.google.com/spreadsheets/d/1uT6RpkIGcMbIyyzayK4Q0JABad2h6gUvW8Hb9JQ61Rc/edit?usp=sharing

**Pull request closed without merging**
